language: node_js
node_js:
 - "node"
deploy:
  provider: gae
  keyfile: veload-9badc1235d9e.json
  project: veload
before_install:
- openssl aes-256-cbc -K $encrypted_028b3f96138f_key -iv $encrypted_028b3f96138f_iv
  -in veload-9badc1235d9e.json.enc -out veload-9badc1235d9e.json -d
env:
  - CXX=g++-4.8
cache: npm
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
after_success:
  - provider : script
    script: bash deploy/rollbar.sh $rollbar_key

branches:
  only:
  - master