language: node_js
deploy:
  provider: gae
  keyfile: veload-9badc1235d9e.json
  project: veload
before_install:
- openssl aes-256-cbc -K $encrypted_028b3f96138f_key -iv $encrypted_028b3f96138f_iv
  -in veload-9badc1235d9e.json.enc -out veload-9badc1235d9e.json -d